export type Faq = { q: string; a: string; tags: string[] }

export const faqs: Faq[] = [
  { q: "What are research peptides?", tags: ["research"], a: "Research peptides are short chains of amino acids manufactured for use as reference materials and investigational tools in laboratory research — receptor pharmacology, cell-culture work, analytical method development and preclinical models. They are supplied strictly for laboratory research use." },
  { q: "Are your products for human consumption?", tags: ["research", "legal"], a: "No. Every product we supply is for laboratory research use only. Products are not intended for human or veterinary consumption, diagnosis, treatment, or prevention of disease." },
  { q: "Are these products approved for medical use?", tags: ["legal"], a: "No. Products in our catalogue are research materials. They are not medicines and have not been approved by any regulatory authority for therapeutic use. Some compound classes are studied in clinical programmes elsewhere, but the materials we supply are for laboratory research only." },
  { q: "What purity level do your products have?", tags: ["quality"], a: "Our peptides are manufactured to a ≥ 98% purity specification, verified by RP-HPLC with identity confirmed by mass spectrometry. Batch-specific figures appear on the Certificate of Analysis for that batch." },
  { q: "How is purity verified?", tags: ["quality"], a: "Each batch undergoes analytical testing including RP-HPLC for purity and mass spectrometry for identity confirmation, alongside in-process controls during synthesis and lyophilization." },
  { q: "Do you provide COAs?", tags: ["quality", "coa"], a: "Yes — a batch-specific Certificate of Analysis accompanies every released batch. You can verify a batch number on our COA Verification page or request the document for your order from support." },
  { q: "How can I verify a batch?", tags: ["coa"], a: "Enter the batch number printed on your vial on the COA Verification page. If the batch is in our released registry, the record and document will be shown. If a batch does not appear, contact support with your order number." },
  { q: "What payment methods do you accept?", tags: ["orders", "payment"], a: "Currently enabled at checkout: UPI and bank transfer. Card and net-banking payments will appear at checkout as soon as they are enabled on our payment gateway. Only methods actually enabled on the live checkout are shown." },
  { q: "What is your refund policy?", tags: ["orders", "refunds"], a: "Damaged, incorrect or missing items are eligible for replacement or refund when reported within 48 hours of delivery with photos of the packaging and vials. Because research compounds are temperature-sensitive, opened or correctly-supplied products cannot be returned. See the Returns & Refunds page for the full policy." },
  { q: "How long does shipping take?", tags: ["shipping"], a: "Orders are dispatched after payment confirmation, with tracking provided on every consignment. Dispatch and delivery estimates are confirmed with your order confirmation and vary by destination." },
  { q: "How can I track my order?", tags: ["shipping", "orders"], a: "A tracking number is emailed once your order is dispatched. If you have not received tracking within the dispatch window, contact support with your order number." },
  { q: "Do you offer bulk pricing or wholesale?", tags: ["wholesale"], a: "Yes. Laboratories, institutions and distributors can request volume pricing through the Research Supply & Wholesale page. Quotations reflect quantity, documentation requirements and recurring-supply arrangements." },
  { q: "Do you ship internationally?", tags: ["shipping"], a: "Yes — we ship worldwide with tracked, insured, temperature-stable packaging following IATA guidelines. Prices are listed in INR; international cards are converted at checkout by your card issuer. Buyers are responsible for confirming that importation of research materials is permitted in their jurisdiction." },
  { q: "How should research compounds be stored?", tags: ["handling"], a: "Lyophilized peptides are typically stored at −20 °C, protected from light and moisture. The storage specification for each product appears on its product page and its documentation." },
  { q: "How do I contact support?", tags: ["support"], a: "Email us or use the Research Support panel on any page. Our team responds Monday–Friday, 9:00 AM – 6:00 PM (GMT)." },
  { q: "Can I request a compound that isn't listed?", tags: ["orders"], a: "Yes — submit a custom research request via the Wholesale page with the compound name, CAS or sequence if known, and required quantity. We will confirm whether we can supply it; availability is never guaranteed until quoted." },
  { q: "What is your Research Use Only policy?", tags: ["legal"], a: "All products are supplied exclusively for laboratory research. By ordering, you confirm the materials will be used for research purposes only, by suitably qualified individuals, and not for any form of human or veterinary use. Orders that indicate otherwise will be refused." },
]
